
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: ddrmc803ico0jt
  username: qolixqyfpbyhqy
  password: Hl9RGBYQCUNtgoDADdW7u2QtU1
  host: ec2-79-125-21-70.eu-west-1.compute.amazonaws.com
  port: 5432