
development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d9u4ck96bth0c3
  username: glhquzvpmvhfcm
  password: JVWeC9k3ajzOrlleqB6avec1zN
  host: ec2-50-19-219-235.compute-1.amazonaws.com
  port: 5432
